#
# Karma Reviewing.
#
ccdn_forum_karma_show_all:
    pattern: /{_locale}/karma/show
    defaults: { _controller: CCDNForumKarmaBundle:Review:show, _locale: en, page: 1 }

ccdn_forum_karma_show_all_paginated:
    pattern: /{_locale}/karma/show/page/{page}
    defaults: { _controller: CCDNForumKarmaBundle:Review:show, _locale: en, page: 1 }

#
# Karma Rate.
#
ccdn_forum_karma_rate:
    pattern: /{_locale}/karma/post/{post_id}/rate
    defaults: { _controller: CCDNForumKarmaBundle:Rate:rate, _locale: en }
